downloader/urls.py
from django.urls import path
# Download view
from downloader import views
from .views import downloader

app_name = 'downloader'

urlpatterns = [
	# path('demo', demo_view, name='demo'),
	path('', views.index, name='index'),
	path('search', views.index, name='index'),
	path('how_download', views.how_download, name='how_download'),
	path('download_video_itag', views.downloader, name='download_video'),
]

videodownloader/urls.py
from django.contrib import admin
from django.urls import path, include
# from videodownloader import views

from downloader import urls as downloader_app_urls
# from django.urls import re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('downloadByItag', views.download_By_Itag, name="downloadByItag"),
    path('', include(downloader_app_urls)),
    path('celery-progress/', include('celery_progress.urls')),
]

downloader/models.py
from django.db import models

# Create your models here.

downloader/views.py
from django.shortcuts import render
from downloader.task import download_video
from django.http import JsonResponse

import pafy
# Create your views here.

def index(request):
    if request.method == 'POST':
        url = request.POST.get('link')
        video = pafy.new(url)
        formatos = video.streams
        audios = video.audiostreams
        all_stream = video.allstreams
        return render(request, 'index.html', {'video': video, 'streams': formatos, 'audios': audios, 'all_streams': all_stream})
    return render(request,'index.html')

def downloader(request):
    if request.method == 'GET':
        itag = request.GET.get('itag')
        id_video = request.GET.get('id-video')
        url = 'https://www.youtube.com/watch?v=' + id_video
        download_task = download_video.delay(url, itag)
        data = {'task_id': download_task.task_id}
        return JsonResponse(data)
    return render(request, 'progress.html')

def how_download(request):
    return render(request, 'how_download.html')

videodownloader/views.py
# from django.template import loader, RequestContext
# from django.shortcuts import render, render_to_response

# import os.path
# # from django.contrib import messages
# from django.http import HttpResponse
# # Descarga 
# import pafy
# # AJAX petition
# from django.http import JsonResponse
# # from django.core.exceptions import SuspiciousOperation

# from celery import shared_task, task
# from celery_progress.backend import ProgressRecorder
# import time

# def index(request):
#     if request.method == 'POST':
#         url = request.POST.get('link')
#         video = pafy.new(url)
#         formatos = video.streams
#         return render(request, 'index.html', {'video': video, 'streams': formatos})
#     return render(request,'index.html')
   
# def mycb(total, recvd, ratio, rate, eta):
#     print(recvd, ratio, eta)

# def download_By_Itag(request):
#     if request.method == 'GET':
#         itag = request.GET.get('itag')
#         id_video = request.GET.get('id-video')
#         url = 'https://www.youtube.com/watch?v=' + id_video
#         video = pafy.new(url)
#         streams = video.streams
#         home_dir = os.path.expanduser('~')
#         dir_final = home_dir + '/Downloads/'
#         for s in streams:
#             if(s.itag == itag):
#                 print("Descargando: " + video.title + '.' + s.extension)
#                 print("Stream: " + s.itag)
#                 s.download(filepath = dir_final, callback = mycb)
#                 break
#             else:
#                 print("No se encontro el Stream")

#         data = {'valueNew': "Iniciando Descarga"}
#         return JsonResponse(data)

# @task
# def my_task():

#     print("step: 1")
#     i = 0
#     while(i < 1000):
#         print("step: 2")
#         i = i + 1
#     print("Finish")

#     return 'work is complete'

# def prueba(request):
#     if request.method == 'GET':
#         print("I'am entering...")
#         my_task.delay()
#         print("I'am leaving...")
    
#         # result = my_task.delay(10)
#         data = {'valueNew': "Iniciando Descarga"}
#         return JsonResponse(data)
#         # return HttpResponse('work kicked off!')


# from time import sleep
# from celery import shared_task, current_task
# from celery import task

# # @shared_task
# @task
# def timer_working():
#     print("ENTRE")
#     i = 0
#     while(i <= 10000000):
#         # process_percent = int(100 * float(i) / float(n))
#         i += 1
#         # current_task.update_state(state='PROGRESS',
#         # meta={'process_percent': process_percent})
#         # print(process_percent)
#         print(i)
#         sleep(1)
#     return ("Done")

# def timer(request):
#     print("VOY A ENTRAR")
#     timer_working.delay()
#     print("SALÍ")
#     return render(request, 'timer.html')
#     # , {'text' : 'Iniciated work'}

videodownloader/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


    <script src="https://use.fontawesome.com/6227a71526.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous"> 

    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
    <title>Video Downloader</title>
  </head>
  <body>
	<!-- Navegation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand" href="search">
          <i class="fas fa-file-download" aria-hidden="true"></i>
          Video Downloader</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="how_download" target="_blank">How to Download?<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">More</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact us</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown link
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
    </nav>


{% block body %}
	
{% endblock body %}
	
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>  

    <script src="{% static 'js/main.js' %}"></script>
  	<script src="{% static 'celery_progress/celery_progress.js' %}"></script>

  </body>
</html>

videodownloader/templates/display_progress.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h2>Done!</h2>

	<div class='progress-wrapper'>
		<div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
	</div>
	<div id="progress-bar-message">Waiting for progress to start...</div>

	<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
	<script>
		document.addEventListener("DOMContentLoaded", function () {
			var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
			CeleryProgressBar.initProgressBar(progressUrl);
		});
	</script>
</body>
</html>

videodownloader/templates/download.html
{% extends "base.html" %}
{% load static %}

{% block demo %}
<!-- Reset Form -->
<a href="{% url 'downloader:download_video' %}" role="button" class="btn btn-primary btn-lg btn-block" style="border-radius: 0px;"><b>RESET</b></a>

<!-- Download Form -->
<div class="container text-center" style="padding-top: 20px;">
	<form action="{% url 'downloader:download_video' %}" method="post" style="display: inline;">
		{% csrf_token %}
		<button class="btn btn-primary" type="submit" style="width:120px;">
			<strong>Download</strong>
		</button>
	</form>
</div>

<!-- Download Status -->
<div class="container" style="padding-top: 20px;">
	<div class="card" style="height: 120px;">
		{% block progress %}{% endblock progress %}
	</div>
</div>
{% endblock %}

videodownloader/templates/how_download.html
{% extends "base.html" %}
{% load static %}


{% block body %}
    
    <div class="block-content">
        <h1>How Download?</h1>
        <div class="img-and-text">
            <img src="{% static 'img/video files.png' %}" alt="video-files">
            <div class="text">
                <h2>Instructions</h2>
                <ol>
                    <!-- <li>Search by name or directly paste the link of video you want to convert</li> -->
                    <li>Paste the link of the YouTube video you want to download.</li>
                    <li>Click "Search" button to begin search process.</li>
                    <li>Select the video/audio format you want to download, then click "Download" button.</li>
                    <li>Wait for the download to complete.</li>
                </ol>
            </div>
        </div>
        <div class="img-and-text">
            <div class="text">
                <h2>Where is my video?</h2>
                <p>Once your download is complete you will be able to find your video in a folder inside your download directory with the name "VideoDownloader".</p>
                <p>For example: <span class="directory">Downloads/VideoDownloader/My_video.mp4</span></p>
            </div>
            <img src="{% static 'img/my files.png' %}" alt="video-files">
        </div>
    </div>

{% endblock body %}
    

videodownloader/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block body %}

  <div class="block-content">
    <h1>Download YouTube video and audio online.</h1>

    <!-- Search form -->
    <form class="form-inline d-flex justify-content-center md-form form-sm mt-0" method = "POST">{% csrf_token %}
      <i class="fas fa-search icon-search" aria-hidden="true"></i>
      <input class="form-control form-control-sm ml-3 w-75" type="url" placeholder="Search or paste URL here..." aria-label="Search" name = "link" id="Search">
      <button type = "submit" class = "btn btn-outline-success"> Search </button> 
    </form>
  </div>

  {% if all_streams %}
  <!-- Video Preview -->
<div class="container block-all">
  <div>
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{{video.bigthumb}}" alt="miniature - {{video.title}}">
    <div class="card-body">
      <h5 class="card-title">{{video.title}}</h5> 
      <!-- Podemos limitar el no. de caracteres de salida con |slice:":35" -->
      <div class="dropdown-divider"></div>
      <h6 class="card-subtitle mb-2 text-muted">{{video.author|slice:":25"}}</h6>
      <!-- <a href="#" class="btn btn-primary">Download best quality</a> -->
    </div>
  </div>
</div>
  <!-- Downloads menu -->
  <div class="block-content">
    <div class="container">
      <div class="row purple-block">
        <div class="col-sm-3 tab-control md-col-active" onclick="tabChange('#table-1', '#tab-control-1')" id="tab-control-1">
          <i class="fas fa-film"></i> 
          Video
        </div>
        <div class="col-sm-3 tab-control" onclick="tabChange('#table-2', '#tab-control-2')" id="tab-control-2">
          <i class="fas fa-music"></i> 
          Audio
        </div>
        <!-- <div class="col-sm-3 tab-control" onclick="tabChange('#table-3', '#tab-control-3')" id="tab-control-3">
          <i class="fas fa-closed-captioning"></i>
          Subtitles
        </div> -->
      </div>
      
      <!-- table #1 - Video -->
        <div class="row white-block">   
          <div class="table-responsive">     
            
            <table class="table" id="table-1">
              <thead class="thead-light">
                <tr>
                  <th scope="col">Resolution</th>
                  <th scope="col">Size</th>
                  <th scope="col">Extension</th>
                  <th scope="col">Download</th>
                </tr>
              </thead>
              <tbody>
                
                {% for s in streams %}
                  <tr>
                    <td>{{s.resolution}}</td>
                    <td class="td-size">{{s.get_filesize}}</td> 
                    <td>{{s.extension}}</td>                   
                    <td>
                      <!-- Button trigger modal -->
                      <a href="#" class="btn btn-success" onClick="DownloadVideoByItag({{s.itag}}, '{{video.videoid}}')" data-toggle="modal" data-target="#ModalCenter-{{s.itag}}" id="btn-download-{{s.itag}}">
                      <i class="fas fa-arrow-alt-circle-down"></i> Download</a>

                      <a href="#" class="btn btn-info" data-toggle="modal" data-target="#ModalCenter" id="btn-info-{{s.itag}}">
                        <i class="fas fa-eye"></i> See progress</a>
                    </td>
                  </tr>   
                {% endfor %}
                         
              </tbody>
            </table>

              <!-- table #2 - Audio -->    
              <table class="table" id="table-2">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">Size</th>
                    <th scope="col">Extension</th>
                    <th scope="col">Download</th>
                  </tr>
                </thead>
                <tbody>
                  
                  {% for audio in audios %}
                    <tr>
                      <td class="td-size">{{audio.get_filesize}}</td> 
                      <td>{{audio.extension}}</td>                   
                      <td> 
                        <!-- Button trigger modal -->
                        <a href="#" class="btn btn-success" onClick="DownloadVideoByItag({{audio.itag}}, '{{video.videoid}}')" data-toggle="modal" data-target="#ModalCenter" id="btn-download-{{audio.itag}}">
                          <i class="fas fa-arrow-alt-circle-down"></i> Download</a>
    
                        <a href="#" class="btn btn-info" data-toggle="modal" data-target="#ModalCenter" id="btn-info-{{audio.itag}}">
                        <i class="fas fa-eye"></i> See progress</a>
                      </td>
                    </tr>   
                  {% endfor %}                         
                </tbody>
              </table> 


          </div>
        </div>
    </div>
  </div>
</div>                                               

<!-- Modal -->
<div class="modal fade" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Downloading...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        <!-- Progress bar -->
        <div class="progress" style="height: 2px;">
          <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">&nbsp;</div>
        </div>
        <div class="progress-bar-message">
          Waiting for the download to start...
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Okey</button>
      </div>
    </div>
  </div>
</div>

{% endif %} 
    

{% endblock body %}
  

videodownloader/templates/progress.html
{% extends "download.html" %}
{% load static %}
{% block progress %}
<div class="text-center" style="font-size: 14px">
	<div id="progress-bar-message">
	Click the "Download" button
	</div>
</div>
<div class='progress-wrapper' style="padding-top: 10px;">
  <div id='progress-bar' class='progress-bar progress-bar-striped' role='progressbar' style="height:30px; width: 0%; border-radius: 5px">&nbsp;</div>
</div>
<div id="celery-result">
</div>
{% endblock progress %}

{% block progress_bar_js %}
{% if task_id %}
<script type="text/javascript">
	// Progress Bar (JQuery)
	$(function () {
		var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
		CeleryProgressBar.initProgressBar(progressUrl, {})
	});
</script>
{% endif %}
{% endblock progress_bar_js %}

videodownloader/templates/timer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Timer</title>
</head>
<body>
    <h2>Done!</h2>
    <!-- <h2>{{ text }}</h2> -->
</body>
</html>